name: smart_yoga_mat
description: A Flutter app for controlling a smart yoga mat.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  google_fonts: ^5.1.0
  flutter_blue_plus: ^1.5.2
  just_audio: ^0.9.34
  firebase_core: ^2.24.2
  firebase_database: ^10.2.3
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.5
  google_sign_in: ^6.1.5
  fl_chart: ^0.63.0
  lottie: ^2.4.0
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  animate_do: ^3.0.2
  intl: ^0.19.0
  # Removed audioplayers since you have just_audio
  # Removed cached_network_audio_player (doesn't exist)
  # Added cached_network_image for network image caching if needed
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
#  assets:
#    - assets/images/